import Head from "next/head";
import styles from "../styles/Puth.module.css";

import { useCookies } from "react-cookie";
import { useState, useEffect } from "react";

import * as React from 'react';
import Table from '@mui/material/Table';
import TableBody from '@mui/material/TableBody';
import TableCell from '@mui/material/TableCell';
import TableContainer from '@mui/material/TableContainer';
import TableHead from '@mui/material/TableHead';
import TableRow from '@mui/material/TableRow';
import Paper from '@mui/material/Paper';

import { useRouter } from 'next/router'

export default function Home() {
    const [cookies, setCookie, removeCookie] = useCookies(['Member']);

    const router = useRouter()
    const data = router.query
    const [Productp, setProductp] = useState([]);
    const [billDetail, setbillDetail] = useState({});
    const [ProfileDetail, setProfileDetail] = useState([]);
    const [printWOW, setPrint] = useState("Print");

    useEffect(() => {
        if(!data.id)return
        fetch('/api/Bill/' + data.id).then((res) => {
            return res.json()
        }).then((_data) => {
            console.log(55555,_data)
            //console.log(data.results[0].bill_ID)
            setbillDetail(_data)
        })
    }, [data]);

    useEffect(() => {
        fetch('/api/profile/' + cookies['Member']).then((res) => {
            return res.json()
        }).then((data0) => {
            // console.log(data)
            setProfileDetail(data0)
            
        })
    }, []);
    let sum = 0


    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1>SHOPPA</h1>
                <div className={styles.half_left_div}>
                    <hr className={styles.hr_big} />
                    <h2>ISSUES TO</h2>
                    <hr className={styles.hr_small} />
                    <div className={styles.puthfix}>
                        <h4>COMPANY NAME</h4>
                    </div>
                    <p className={styles.info}>SHOPPA Co.Ltd.</p>
                    <hr className={styles.hr_invis} />
                    <div className={styles.puthfix}>
                        <h4>ADDRESS</h4>
                    </div>
                    <p className={styles.info}>
                        126 Pracha Uthit Rd., Bang Mod, Thung Khru, Bangkok 10140, Thailand
                    </p>
                    <hr className={styles.hr_small} />
                    <div className={styles.puthfix}>
                        <h4>BILL ID</h4>
                    </div>

                    <p className={styles.info}>{(billDetail.results && billDetail.results.length > 0) ? billDetail.results[0].Bill_ID : ''}</p>
                    <hr className={styles.hr_med} />
                    <div className={styles.puthfix}>
                        <h4>DATE ISSUED</h4>
                    </div>

                    <p className={styles.info}>{(billDetail.results && billDetail.results.length > 0) ? billDetail.results[0].Bill_Date.substr(0, 10) : ''}</p>
                    <hr className={styles.hr_small} />
                    <div className={styles.puthfix}>
                        <h4>DATE PRINTED</h4>
                    </div>
                    <p className={styles.info}>{new Date().toISOString().substr(0, 10)}</p>
                </div>
                <div className={styles.half_right_div}>
                    <hr className={styles.hr_big} />
                    <h2>PAYABLE TO</h2>
                    <hr className={styles.hr_small} />
                    <div className={styles.puthfix}>
                        <h4>CUSTOMER NAME</h4>
                    </div>
                    <p className={styles.info}>{ProfileDetail.length > 0 && ProfileDetail[0].Member_FName + " " + ProfileDetail[0].Member_LName}</p>
                    <hr className={styles.hr_invis} />
                    <div className={styles.puthfix}>
                        <h4>PHONE</h4>
                    </div>
                    <p className={styles.info}>{ProfileDetail.length > 0 && ProfileDetail[0].Member_Telephone}</p>
                    <hr className={styles.hr_invis} />

                    <div className={styles.puthfix}>
                        <h4>CUSTOMER ID</h4>
                    </div>
                    <p className={styles.info}>{ProfileDetail.length > 0 && ProfileDetail[0].Member_ID}</p>
                    <hr className={styles.hr_invis} />

                    <div className={styles.puthfix}>
                        <h4>BANK</h4>
                    </div>
                    <p className={styles.info}>{(billDetail.results2 && billDetail.results2.length > 0) ? billDetail.results2[0].BranchBank_Name : ''}</p>
                    <hr className={styles.hr_small} />

                    <div className={styles.puthfix}>
                        <h4>ADDRESS</h4>
                    </div>
                    <p className={styles.info}>
                        {ProfileDetail.length > 0 && ProfileDetail[0].Member_Address}
                    </p>
                </div>
                <hr className={styles.hr_big} />
                <div className={styles.bottom_div}>
                    <h2>CHARGES</h2>

                    {/*  */}
                    <TableContainer component={Paper}>
                        <Table sx={{ minWidth: 700 }} aria-label="spanning table">
                            <TableHead>
                                <TableRow>
                                    <TableCell align="center" colSpan={5}>
                                        Details
                                    </TableCell>
                                    <TableCell align="right" colSpan={3}>Price</TableCell>
                                </TableRow>
                                <TableRow>
                                    <TableCell colSpan={1}>Description</TableCell>
                                    <TableCell colSpan={5} align="center">Quantity</TableCell>
                                    <TableCell colSpan={2} align="right">Sum</TableCell>
                                </TableRow>
                            </TableHead>
                            <TableBody>
                                {
                                    (billDetail.results3) && billDetail.results3.map((row, i) => (
                                        sum += row.OrderItem_Price * row.OrderItem_Total,
                                            //setProductp(datadata)
                                            <TableRow rowSpan={1} key={i}>
                                                <TableCell colSpan={1} align="left">{row.Product_Name}</TableCell>
                                                <TableCell colSpan={5} align="center">{row.OrderItem_Total}</TableCell>
                                                <TableCell colSpan={2} align="right">{row.OrderItem_Price}</TableCell>
                                            </TableRow>))
                                }
                            </TableBody>
                            <TableRow>

                                <TableCell colSpan={6} ></TableCell>
                                <TableCell colSpan={1} >Subtotal</TableCell>
                                <TableCell align="right">{sum}</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell colSpan={6}></TableCell>
                                <TableCell align="left" colSpan={1}>Tax 7%</TableCell>
                                <TableCell align="right">{Math.floor(sum * 0.07)}</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell colSpan={6}></TableCell>
                                <TableCell align="left" colSpan={1}>Total</TableCell>
                                <TableCell colSpan={3} align="right">{ sum + Math.floor(sum * 0.07)}</TableCell>
                            </TableRow>
                        </Table>
                    </TableContainer>
                    {/*  */}

                    <br></br>
                </div>
                <hr className={styles.hr_big} />
                <br></br>
                <div>
                    <p>This is a computer generated invoice. No signature is necessary.</p>

                </div>
                <div className={styles.last_div + ' ' + styles.marRight}>
                    <hr className={styles.hr_small} />
                    <div className={styles.puthfix}>
                        <h4>PHONE</h4>
                    </div>
                    <p className={styles.last_info}>095 472 9142</p>
                    <hr className={styles.hr_big} />
                </div>
                <div className={styles.last_div + ' ' + styles.marRight}>
                    <hr className={styles.hr_small} />
                    <div className={styles.puthfix}>
                        <h4>EMAIL</h4>
                    </div>
                    <p className={styles.last_info}>shoppa@shoppa.com</p>
                    <hr className={styles.hr_big} />
                </div>
                <div className={styles.last_div}>
                    <hr className={styles.hr_small} />
                    <div className={styles.puthfix}>
                        <h4>WEBSITE</h4>
                    </div>
                    <p className={styles.last_info}>https://kmutt.in.th/Shoppa</p>
                    <hr className={styles.hr_big} />
                </div>
                {
                    (printWOW) &&
                    <button onClick={() => { setPrint(""); setTimeout(window.print, 1) }}> {printWOW} </button>
                }
            </main >

            <footer className={styles.footer}></footer>


        </div >
    )
}