import Head from "next/head";
import styles from "../styles/Puth.module.css";

import { useCookies } from "react-cookie";
import { useState , useEffect } from "react";

import * as React from 'react';
import Table from '@mui/material/Table';
import TableBody from '@mui/material/TableBody';
import TableCell from '@mui/material/TableCell';
import TableContainer from '@mui/material/TableContainer';
import TableHead from '@mui/material/TableHead';
import TableRow from '@mui/material/TableRow';
import Paper from '@mui/material/Paper';
import BasicSelectProduct from "./comps/selectbankcomp";

export default function Home() {
    const [cookies, setCookie, removeCookie] = useCookies(['Member', 'Cart']);
    if(cookies['Member']){
        const data = cookies['Member']
    }
    const [profileDetail, setProfileDetail] = useState([]);
    useEffect(() => {
        fetch('/api/profile/' + data).then((res) => {
            return res.json()
        }).then((data) => {
            console.log(data)
            setProfileDetail(data) 
        })
    }, []);
    
    const cart = cookies['Cart']
    console.log(cart)
    let a = 0, sum = 0
    if (cookies['Cart']) {
        while (cookies['Cart'][a]) {
            sum += cookies['Cart'][a].price
            a++
        }
    }
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1>SHOPPA</h1>
                <div className={styles.half_left_div}>
                    <hr className={styles.hr_big} />
                    <h2>ISSUES TO</h2>
                    <hr className={styles.hr_small} />
                    <div className={styles.puthfix}>
                        <h3>COMPANY NAME</h3>
                    </div>
                    <p className={styles.info}>SHOPPA Co.Ltd.</p>
                    <hr className={styles.hr_invis} />
                    <div className={styles.puthfix}>
                        <h3>ADDRESS</h3>
                    </div>
                    <p className={styles.info}>
                        126 Pracha Uthit Rd., Bang Mod, Thung Khru, Bangkok 10140, Thailand
                    </p>
                    <hr className={styles.hr_small} />
                    <div className={styles.puthfix}>
                        <h3>BILL ID</h3>
                    </div>

                    <p className={styles.info}>BL1234567</p>
                    <hr className={styles.hr_med} />
                    <div className={styles.puthfix}>
                        <h3>DATE ISSUED</h3>
                    </div>

                    <p className={styles.info}>24 Oct, 2021</p>
                    <hr className={styles.hr_small} />
                    <div className={styles.puthfix}>
                        <h3>DATE DUE</h3>
                    </div>
                    <p className={styles.info}>12 Nov, 2021</p>
                    <hr className={styles.hr_small} />
                    <div className={styles.puthfix}>
                        <h3>CATEGORY</h3>
                    </div>
                    <p className={styles.info}>Shoes</p>
                </div>
                <div className={styles.half_right_div}>
                    <hr className={styles.hr_big} />
                    <h2>PAYABLE TO</h2>
                    <hr className={styles.hr_small} />
                    <div className={styles.puthfix}>
                        <h3>CUSTOMER NAME</h3>
                    </div>
                    <p className={styles.info}>{profileDetail.length > 0 && profileDetail[0].Member_FName + " " + profileDetail[0].Member_LName}</p>
                    <hr className={styles.hr_invis} />
                    <div className={styles.puthfix}>
                        <h3>PHONE</h3>
                    </div>
                    <p className={styles.info}>{profileDetail.length > 0 && profileDetail[0].Member_Telephone}</p>
                    <hr className={styles.hr_invis} />

                    <div className={styles.puthfix}>
                        <h3>CUSTOMER ID</h3>
                    </div>
                    <p className={styles.info}>{profileDetail.length > 0 && profileDetail[0].Member_ID}</p>
                    <hr className={styles.hr_invis} />

                    <div className={styles.puthfix}>
                        <h3>BANK</h3>
                    </div>
                    <p className={styles.info}>Kasikorn Bank</p>
                    <hr className={styles.hr_small} />

                    <div className={styles.puthfix}>
                        <h3>BILL ID</h3>
                    </div>
                    <p className={styles.info}>BL1234567</p>
                    <hr className={styles.hr_small} />

                    <div className={styles.puthfix}>
                        <h3>ADDRESS</h3>
                    </div>
                    <p className={styles.info}>
                        {profileDetail.length > 0 && profileDetail[0].Member_Address}
                    </p>
                </div>
                <hr className={styles.hr_big} />
                <div className={styles.bottom_div}>
                    <h2>CHARGES</h2>

                    {/*  */}
                    <TableContainer component={Paper}>
                        <Table sx={{ minWidth: 700 }} aria-label="spanning table">
                            <TableHead>
                            <TableRow>
                                <TableCell align="center" colSpan={4}>
                                Details
                                </TableCell>
                                <TableCell align="right">Price</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell>Description</TableCell>
                                <TableCell align="right"></TableCell>
                                <TableCell align="left">Price</TableCell>
                                <TableCell align="center">Quantity</TableCell>
                                <TableCell align="right">Sum</TableCell>
                            </TableRow>
                            </TableHead>
                            <TableBody>
                            {(cart) && cart.map((row, i) => (
                                <TableRow key={i}>
                                <TableCell></TableCell>
                                <TableCell align="right">{row.name}</TableCell>
                                <TableCell align="left">{row.qty}</TableCell>
                                <TableCell align="center">THB</TableCell>
                                <TableCell align="right">{row.price}</TableCell>
                                </TableRow>
                            ))}
                            <TableRow>
                                <TableCell rowSpan={4} />
                                <TableCell colSpan={3}>Subtotal</TableCell>
                                <TableCell align="right">{sum}</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell >Tax</TableCell>
                                <TableCell align="left" colSpan={2}>7%</TableCell>
                                <TableCell align="right">{sum * 0.07}</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell colSpan={3}>Total</TableCell>
                                <TableCell align="right">{sum + sum * 0.07}</TableCell>
                            </TableRow>
                            </TableBody>
                        </Table>
                        </TableContainer>
                    {/*  */}
                    
                    <br></br>
                </div>
                <hr className={styles.hr_big} />
                <br></br>
                <div>
                    <p>This is a computer generated invoice. No signature is necessary.</p>

                </div>
                <div className={styles.last_div + ' ' + styles.marRight}>
                    <hr className={styles.hr_small} />
                    <div className={styles.puthfix}>
                        <h3>PHONE</h3>
                    </div>
                    <p className={styles.last_info}>095 472 9142</p>
                    <hr className={styles.hr_big} />
                </div>
                <div className={styles.last_div + ' ' + styles.marRight}>
                    <hr className={styles.hr_small} />
                    <div className={styles.puthfix}>
                        <h3>EMAIL</h3>
                    </div>
                    <p className={styles.last_info}>shoppa@shoppa.com</p>
                    <hr className={styles.hr_big} />
                </div>
                <div className={styles.last_div}>
                    <hr className={styles.hr_small} />
                    <div className={styles.puthfix}>
                        <h3>WEBSITE</h3>
                    </div>
                    <p className={styles.last_info}>https://kmutt.in.th/Shoppa</p>
                    <hr className={styles.hr_big} />
                </div>
                <BasicSelectProduct></BasicSelectProduct>
            </main>

            <footer className={styles.footer}></footer>
            <button onClick={() => window.print()}> Print </button>

        </div>
    )
}