import Head from "next/head";
import styles from "../styles/Home.module.css";
import DenseTable from "./component/table";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>SHOPPA</h1>
        <div className={styles.half_left_div}>
          <hr className={styles.hr_big} />
          <h2>ISSUES TO</h2>
          <hr className={styles.hr_small} />
          <div className={styles.puthfix}>
            <h3>COMPANY NAME</h3>
          </div>
          <p className={styles.info}>SHOPPA Co.Ltd.</p>
          <hr className={styles.hr_invis} />
          <div className={styles.puthfix}>
            <h3>ADDRESS</h3>
          </div>
          <p className={styles.info}>
            126 Pracha Uthit Rd., Bang Mod, Thung Khru, Bangkok 10140, Thailand
          </p>
          <hr className={styles.hr_small} />
          <div className={styles.puthfix}>
            <h3>BILL ID</h3>
          </div>

          <p className={styles.info}>BL1234567</p>
          <hr className={styles.hr_med} />
          <div className={styles.puthfix}>
            <h3>DATE ISSUED</h3>
          </div>

          <p className={styles.info}>24 Oct, 2021</p>
          <hr className={styles.hr_small} />
          <div className={styles.puthfix}>
            <h3>DATE DUE</h3>
          </div>
          <p className={styles.info}>12 Nov, 2021</p>
          <hr className={styles.hr_small} />
          <div className={styles.puthfix}>
            <h3>CATEGORY</h3>
          </div>
          <p className={styles.info}>Shoes</p>
        </div>
        <div className={styles.half_right_div}>
          <hr className={styles.hr_big} />
          <h2>PAYABLE TO</h2>
          <hr className={styles.hr_small} />
          <div className={styles.puthfix}>
            <h3>CUSTOMER NAME</h3>
          </div>
          <p className={styles.info}>Juhi Chitravanshi</p>
          <hr className={styles.hr_invis} />
          <div className={styles.puthfix}>
            <h3>PHONE</h3>
          </div>
          <p className={styles.info}>0123456789012</p>
          <hr className={styles.hr_invis} />

          <div className={styles.puthfix}>
            <h3>CUSTOMER ID</h3>
          </div>
          <p className={styles.info}>M1234567</p>
          <hr className={styles.hr_invis} />

          <div className={styles.puthfix}>
            <h3>BANK</h3>
          </div>
          <p className={styles.info}>Kasikorn Bank</p>
          <hr className={styles.hr_small} />

          <div className={styles.puthfix}>
            <h3>BILL ID</h3>
          </div>
          <p className={styles.info}>BL1234567</p>
          <hr className={styles.hr_small} />

          <div className={styles.puthfix}>
            <h3>ADDRESS</h3>
          </div>
          <p className={styles.info}>
            A123, First Floor, Neighboury McNeighbourhood, City—123456, State (India)
          </p>
        </div>
        <hr className={styles.hr_big} />
        <div className={styles.bottom_div}>
          <h2>CHARGES</h2>

          <DenseTable />
          <br></br>
        </div>
        <hr className={styles.hr_big} />
        <br></br>
        <div>
          <p>This is a computer generated invoice. No signature is necessary.</p>

        </div>
        <div className={styles.last_div+ ' ' + styles.marRight}>
        <hr className={styles.hr_small} />
        <div className={styles.puthfix}>
            <h3>PHONE</h3>
          </div>
          <p className={styles.last_info}>095 472 9142</p>
          <hr className={styles.hr_big} />
        </div>
        <div className={styles.last_div+ ' ' + styles.marRight}>
        <hr className={styles.hr_small} />
        <div className={styles.puthfix}>
            <h3>PHONE</h3>
          </div>
          <p className={styles.last_info}>095 472 9142</p>
          <hr className={styles.hr_big} />
        </div>
        <div className={styles.last_div}>
        <hr className={styles.hr_small} />
        <div className={styles.puthfix}>
            <h3>PHONE</h3>
          </div>
          <p className={styles.last_info}>095 472 9142</p>
          <hr className={styles.hr_big} />
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
